services:
  gravitino:
    image: apache/gravitino-iceberg-rest:1.3.1-rc3
    ports:
      - "9001:9001"
    environment:
      GRAVITINO_MEM: -Xms1g -Xmx4g -XX:MaxMetaspaceSize=1g
      GRAVITINO_ICEBERG_REST_CATALOG_BACKEND: memory
      GRAVITINO_ICEBERG_REST_IO_IMPL: org.apache.iceberg.aws.s3.S3FileIO
      GRAVITINO_ICEBERG_REST_WAREHOUSE: s3://warehouse/
      GRAVITINO_ICEBERG_REST_CREDENTIAL_PROVIDERS: s3-secret-key
      GRAVITINO_ICEBERG_REST_S3_ACCESS_KEY: admin
      GRAVITINO_ICEBERG_REST_S3_SECRET_KEY: password
      GRAVITINO_ICEBERG_REST_S3_ENDPOINT: http://seaweedfs:9000
      GRAVITINO_ICEBERG_REST_S3_REGION: us-east-1
      GRAVITINO_ICEBERG_REST_S3_PATH_STYLE_ACCESS: "true"
    depends_on:
      s3-init:
        condition: service_completed_successfully

  seaweedfs:
    image: chrislusf/seaweedfs:4.47
    ports:
      - "9000:9000"
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
    command: ["server", "-dir=/data", "-ip=seaweedfs", "-s3", "-s3.port=9000"]

  s3-init:
    image: amazon/aws-cli:2.36.44
    depends_on:
      - seaweedfs
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: us-east-1
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        until aws --endpoint-url http://seaweedfs:9000 s3 mb s3://warehouse; do
          echo 'Waiting for SeaweedFS...'
          sleep 2
        done
