name: Cloud functional tests
on:
  schedule:
    - cron:  '0 3 * * 1,3,5' # runs at 3am monday wednesday and friday
  workflow_dispatch:
    inputs:
      duckdb_ref:
        description: 'DuckDB branch name or commit hash'
        required: false
        default: 'main'
      duckdb_iceberg_ref:
        description: 'duckdb-iceberg branch name or commit hash'
        required: false
        default: 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  cloud-tests:
    uses: ./.github/workflows/CloudTestingReusable.yml
    with:
      duckdb_ref: ${{ github.event.inputs.duckdb_ref || 'main' }}
      duckdb_iceberg_ref: ${{ github.event.inputs.duckdb_iceberg_ref || 'main' }}
    secrets: inherit
